name = "Another Edition"
author = "thePlaceholder"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cfe2ce12ee2c882a409d61f78c6dc53d4d6f63c59f0d20cdeb68c8620fbaff7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
datapack-folder = "global_packs/required_data"
