name = "Another Edition"
author = "thePlaceholder"
version = "0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06f3d13172a981236d29fbeb6f74506b636ead0cda1a4cfccb95ea91ac9121a0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"

[options]
datapack-folder = "global_packs/required_data"
